---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class AudioReverbPreset : Enum
---@field public value__ number 
---@field public Off number 
---@field public Generic number 
---@field public PaddedCell number 
---@field public Room number 
---@field public Bathroom number 
---@field public Livingroom number 
---@field public Stoneroom number 
---@field public Auditorium number 
---@field public Concerthall number 
---@field public Cave number 
---@field public Arena number 
---@field public Hangar number 
---@field public CarpetedHallway number 
---@field public Hallway number 
---@field public StoneCorridor number 
---@field public Alley number 
---@field public Forest number 
---@field public City number 
---@field public Mountains number 
---@field public Quarry number 
---@field public Plain number 
---@field public ParkingLot number 
---@field public SewerPipe number 
---@field public Underwater number 
---@field public Drugged number 
---@field public Dizzy number 
---@field public Psychotic number 
---@field public User number 
local AudioReverbPreset={ }
---
UnityEngine.AudioReverbPreset = AudioReverbPreset