---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class AudioReverbZone : Behaviour
---@field public minDistance number 
---@field public maxDistance number 
---@field public reverbPreset number 
---@field public room number 
---@field public roomHF number 
---@field public roomLF number 
---@field public decayTime number 
---@field public decayHFRatio number 
---@field public reflections number 
---@field public reflectionsDelay number 
---@field public reverb number 
---@field public reverbDelay number 
---@field public HFReference number 
---@field public LFReference number 
---@field public roomRolloffFactor number 
---@field public diffusion number 
---@field public density number 
local AudioReverbZone={ }
---
UnityEngine.AudioReverbZone = AudioReverbZone