---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class AudioReverbFilter : Behaviour
---@field public lFReference number 
---@field public reverbPreset number 
---@field public dryLevel number 
---@field public room number 
---@field public roomHF number 
---@field public roomRolloffFactor number 
---@field public decayTime number 
---@field public decayHFRatio number 
---@field public reflectionsLevel number 
---@field public reflectionsDelay number 
---@field public reverbLevel number 
---@field public reverbDelay number 
---@field public diffusion number 
---@field public density number 
---@field public hfReference number 
---@field public roomLF number 
---@field public lfReference number 
local AudioReverbFilter={ }
---
UnityEngine.AudioReverbFilter = AudioReverbFilter