---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class ConfigurableJoint : Joint
---@field public secondaryAxis Vector3 
---@field public xMotion number 
---@field public yMotion number 
---@field public zMotion number 
---@field public angularXMotion number 
---@field public angularYMotion number 
---@field public angularZMotion number 
---@field public linearLimitSpring SoftJointLimitSpring 
---@field public angularXLimitSpring SoftJointLimitSpring 
---@field public angularYZLimitSpring SoftJointLimitSpring 
---@field public linearLimit SoftJointLimit 
---@field public lowAngularXLimit SoftJointLimit 
---@field public highAngularXLimit SoftJointLimit 
---@field public angularYLimit SoftJointLimit 
---@field public angularZLimit SoftJointLimit 
---@field public targetPosition Vector3 
---@field public targetVelocity Vector3 
---@field public xDrive JointDrive 
---@field public yDrive JointDrive 
---@field public zDrive JointDrive 
---@field public targetRotation Quaternion 
---@field public targetAngularVelocity Vector3 
---@field public rotationDriveMode number 
---@field public angularXDrive JointDrive 
---@field public angularYZDrive JointDrive 
---@field public slerpDrive JointDrive 
---@field public projectionMode number 
---@field public projectionDistance number 
---@field public projectionAngle number 
---@field public configuredInWorldSpace boolean 
---@field public swapBodies boolean 
local ConfigurableJoint={ }
---
UnityEngine.ConfigurableJoint = ConfigurableJoint