---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class Dof : Enum
---@field public value__ number 
---@field public BodyDofStart number 
---@field public HeadDofStart number 
---@field public LeftLegDofStart number 
---@field public RightLegDofStart number 
---@field public LeftArmDofStart number 
---@field public RightArmDofStart number 
---@field public LeftThumbDofStart number 
---@field public LeftIndexDofStart number 
---@field public LeftMiddleDofStart number 
---@field public LeftRingDofStart number 
---@field public LeftLittleDofStart number 
---@field public RightThumbDofStart number 
---@field public RightIndexDofStart number 
---@field public RightMiddleDofStart number 
---@field public RightRingDofStart number 
---@field public RightLittleDofStart number 
---@field public LastDof number 
local Dof={ }
---
UnityEngine.Dof = Dof