---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class HumanPartDof : Enum
---@field public value__ number 
---@field public Body number 
---@field public Head number 
---@field public LeftLeg number 
---@field public RightLeg number 
---@field public LeftArm number 
---@field public RightArm number 
---@field public LeftThumb number 
---@field public LeftIndex number 
---@field public LeftMiddle number 
---@field public LeftRing number 
---@field public LeftLittle number 
---@field public RightThumb number 
---@field public RightIndex number 
---@field public RightMiddle number 
---@field public RightRing number 
---@field public RightLittle number 
---@field public LastHumanPartDof number 
local HumanPartDof={ }
---
UnityEngine.HumanPartDof = HumanPartDof