---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class Internal_DrawTextureArguments : ValueType
---@field public screenRect Rect 
---@field public sourceRect Rect 
---@field public leftBorder number 
---@field public rightBorder number 
---@field public topBorder number 
---@field public bottomBorder number 
---@field public leftBorderColor Color 
---@field public rightBorderColor Color 
---@field public topBorderColor Color 
---@field public bottomBorderColor Color 
---@field public color Color 
---@field public borderWidths Vector4 
---@field public cornerRadiuses Vector4 
---@field public smoothCorners boolean 
---@field public pass number 
---@field public texture Texture 
---@field public mat Material 
local Internal_DrawTextureArguments={ }
---
UnityEngine.Internal_DrawTextureArguments = Internal_DrawTextureArguments