---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class RuntimePlatform : Enum
---@field public value__ number 
---@field public OSXEditor number 
---@field public OSXPlayer number 
---@field public WindowsPlayer number 
---@field public OSXWebPlayer number 
---@field public OSXDashboardPlayer number 
---@field public WindowsWebPlayer number 
---@field public WindowsEditor number 
---@field public IPhonePlayer number 
---@field public XBOX360 number 
---@field public PS3 number 
---@field public Android number 
---@field public NaCl number 
---@field public FlashPlayer number 
---@field public LinuxPlayer number 
---@field public LinuxEditor number 
---@field public WebGLPlayer number 
---@field public MetroPlayerX86 number 
---@field public WSAPlayerX86 number 
---@field public MetroPlayerX64 number 
---@field public WSAPlayerX64 number 
---@field public MetroPlayerARM number 
---@field public WSAPlayerARM number 
---@field public WP8Player number 
---@field public BB10Player number 
---@field public BlackBerryPlayer number 
---@field public TizenPlayer number 
---@field public PSP2 number 
---@field public PS4 number 
---@field public PSM number 
---@field public XboxOne number 
---@field public SamsungTVPlayer number 
---@field public WiiU number 
---@field public tvOS number 
---@field public Switch number 
---@field public Lumin number 
---@field public Stadia number 
---@field public CloudRendering number 
---@field public GameCoreScarlett number 
---@field public GameCoreXboxOne number 
---@field public PS5 number 
local RuntimePlatform={ }
---
UnityEngine.RuntimePlatform = RuntimePlatform