---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class RenderTextureDescriptor : ValueType
---@field public width number 
---@field public height number 
---@field public msaaSamples number 
---@field public volumeDepth number 
---@field public mipCount number 
---@field public graphicsFormat number 
---@field public stencilFormat number 
---@field public colorFormat number 
---@field public sRGB boolean 
---@field public depthBufferBits number 
---@field public dimension number 
---@field public shadowSamplingMode number 
---@field public vrUsage number 
---@field public flags number 
---@field public memoryless number 
---@field public useMipMap boolean 
---@field public autoGenerateMips boolean 
---@field public enableRandomWrite boolean 
---@field public bindMS boolean 
---@field public useDynamicScale boolean 
local RenderTextureDescriptor={ }
---
UnityEngine.RenderTextureDescriptor = RenderTextureDescriptor