---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class RenderTextureFormat : Enum
---@field public value__ number 
---@field public ARGB32 number 
---@field public Depth number 
---@field public ARGBHalf number 
---@field public Shadowmap number 
---@field public RGB565 number 
---@field public ARGB4444 number 
---@field public ARGB1555 number 
---@field public Default number 
---@field public ARGB2101010 number 
---@field public DefaultHDR number 
---@field public ARGB64 number 
---@field public ARGBFloat number 
---@field public RGFloat number 
---@field public RGHalf number 
---@field public RFloat number 
---@field public RHalf number 
---@field public R8 number 
---@field public ARGBInt number 
---@field public RGInt number 
---@field public RInt number 
---@field public BGRA32 number 
---@field public RGB111110Float number 
---@field public RG32 number 
---@field public RGBAUShort number 
---@field public RG16 number 
---@field public BGRA10101010_XR number 
---@field public BGR101010_XR number 
---@field public R16 number 
local RenderTextureFormat={ }
---
UnityEngine.RenderTextureFormat = RenderTextureFormat