---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class DrivenTransformProperties : Enum
---@field public value__ number 
---@field public None number 
---@field public All number 
---@field public AnchoredPositionX number 
---@field public AnchoredPositionY number 
---@field public AnchoredPositionZ number 
---@field public Rotation number 
---@field public ScaleX number 
---@field public ScaleY number 
---@field public ScaleZ number 
---@field public AnchorMinX number 
---@field public AnchorMinY number 
---@field public AnchorMaxX number 
---@field public AnchorMaxY number 
---@field public SizeDeltaX number 
---@field public SizeDeltaY number 
---@field public PivotX number 
---@field public PivotY number 
---@field public AnchoredPosition number 
---@field public AnchoredPosition3D number 
---@field public Scale number 
---@field public AnchorMin number 
---@field public AnchorMax number 
---@field public Anchors number 
---@field public SizeDelta number 
---@field public Pivot number 
local DrivenTransformProperties={ }
---
UnityEngine.DrivenTransformProperties = DrivenTransformProperties