---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class GameError
---@field public value__ number 
---@field public None number 无错误
---@field public UnKnow number 
---@field public AlreadyRegistered number 
---@field public NotRegister number 
---@field public NotLoad number 
---@field public ConfigueNotRight number 
---@field public NotImplemented number 
---@field public ContextMismatch number 
---@field public ParamNotProvide number 
---@field public Empty number 
---@field public MissingAttribute number 
---@field public PackageCanNotRun number 
---@field public PackageIncompatible number 
---@field public ClassNotFound number 
---@field public FileNotFound number 
---@field public FunctionNotFound number 
---@field public PackageDefNotFound number 
---@field public AssetBundleNotFound number 
---@field public FileReadFailed number 
---@field public NotReturn number 
---@field public InvalidPackageName number 
---@field public RegisterPackageFailed number 
---@field public NotSupportFileType number 
---@field public NetworkError number 
---@field public ExecutionFailed number 
---@field public AccessDenined number 
---@field public IsLoading number 
---@field public SystemPackageNotLoad number 
---@field public UnKnowType number 
---@field public LuaBindCheckFailed number 
---@field public OnlyCanUseInEditor number 
local GameError={ }
---
Ballance2.Sys.Debug.GameError = GameError