---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class LuaVarObjectType
---@field public value__ number 
---@field public None number 
---@field public Vector2 number 
---@field public Vector2Int number 
---@field public Vector3 number 
---@field public Vector3Int number 
---@field public Vector4 number 
---@field public Rect number 
---@field public RectInt number 
---@field public Gradient number 
---@field public Layer number 
---@field public Curve number 
---@field public Color number 
---@field public BoundsInt number 
---@field public Bounds number 
---@field public Object number 
---@field public GameObject number 
---@field public Long number 
---@field public Int number 
---@field public String number 
---@field public Double number 
---@field public Bool number 
local LuaVarObjectType={ }
---指定引入数据的类型
Ballance2.Sys.Bridge.LuaWapper.LuaVarObjectType = LuaVarObjectType