---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class StoreDataType
---@field public value__ number 
---@field public NotSet number 
---@field public Custom number object 类型
---@field public Array number 
---@field public Integer number 
---@field public Long number 
---@field public Float number 
---@field public String number 
---@field public Boolean number 
---@field public Double number 
---@field public Color number 
---@field public Material number 
---@field public Texture number 
---@field public Texture2D number 
---@field public Vector2 number 
---@field public Vector3 number 
---@field public Vector4 number 
---@field public Quaternion number 
---@field public Sprite number 
---@field public Rigidbody number 
---@field public RectTransform number 
---@field public Transform number 
---@field public Camera number 
---@field public GameObject number 
---@field public Object number UnityEngine.Object
---@field public AudioClip number 
---@field public AudioSource number 
---@field public MonoBehaviour number 
local StoreDataType={ }
---数据类型
Ballance2.Sys.Bridge.StoreDataType = StoreDataType