---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class PhysicsJobOptions2D : ValueType
---@field public useMultithreading boolean 
---@field public useConsistencySorting boolean 
---@field public interpolationPosesPerJob number 
---@field public newContactsPerJob number 
---@field public collideContactsPerJob number 
---@field public clearFlagsPerJob number 
---@field public clearBodyForcesPerJob number 
---@field public syncDiscreteFixturesPerJob number 
---@field public syncContinuousFixturesPerJob number 
---@field public findNearestContactsPerJob number 
---@field public updateTriggerContactsPerJob number 
---@field public islandSolverCostThreshold number 
---@field public islandSolverBodyCostScale number 
---@field public islandSolverContactCostScale number 
---@field public islandSolverJointCostScale number 
---@field public islandSolverBodiesPerJob number 
---@field public islandSolverContactsPerJob number 
local PhysicsJobOptions2D={ }
---
UnityEngine.PhysicsJobOptions2D = PhysicsJobOptions2D