---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class EventCommandNames
---@field public Cut string 
---@field public Copy string 
---@field public Paste string 
---@field public SelectAll string 
---@field public DeselectAll string 
---@field public InvertSelection string 
---@field public Duplicate string 
---@field public Rename string 
---@field public Delete string 
---@field public SoftDelete string 
---@field public Find string 
---@field public SelectChildren string 
---@field public SelectPrefabRoot string 
---@field public UndoRedoPerformed string 
---@field public OnLostFocus string 
---@field public NewKeyboardFocus string 
---@field public ModifierKeysChanged string 
---@field public EyeDropperUpdate string 
---@field public EyeDropperClicked string 
---@field public EyeDropperCancelled string 
---@field public ColorPickerChanged string 
---@field public FrameSelected string 
---@field public FrameSelectedWithLock string 
local EventCommandNames={ }
---
UnityEngine.EventCommandNames = EventCommandNames