---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class CharacterInfo : ValueType
---@field public index number 
---@field public uv Rect 
---@field public vert Rect 
---@field public width number 
---@field public size number 
---@field public style number 
---@field public flipped boolean 
---@field public advance number 
---@field public glyphWidth number 
---@field public glyphHeight number 
---@field public bearing number 
---@field public minY number 
---@field public maxY number 
---@field public minX number 
---@field public maxX number 
---@field public uvBottomLeft Vector2 
---@field public uvBottomRight Vector2 
---@field public uvTopRight Vector2 
---@field public uvTopLeft Vector2 
local CharacterInfo={ }
---
UnityEngine.CharacterInfo = CharacterInfo