---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class EventTriggerType : Enum
---@field public value__ number 
---@field public PointerEnter number 
---@field public PointerExit number 
---@field public PointerDown number 
---@field public PointerUp number 
---@field public PointerClick number 
---@field public Drag number 
---@field public Drop number 
---@field public Scroll number 
---@field public UpdateSelected number 
---@field public Select number 
---@field public Deselect number 
---@field public Move number 
---@field public InitializePotentialDrag number 
---@field public BeginDrag number 
---@field public EndDrag number 
---@field public Submit number 
---@field public Cancel number 
local EventTriggerType={ }
---
UnityEngine.EventSystems.EventTriggerType = EventTriggerType