---@diagnostic disable: duplicate-set-field, undefined-doc-class, undefined-doc-name, duplicate-doc-field
---@class ExecuteEvents
---@field public pointerEnterHandler EventFunction`1 
---@field public pointerExitHandler EventFunction`1 
---@field public pointerDownHandler EventFunction`1 
---@field public pointerUpHandler EventFunction`1 
---@field public pointerClickHandler EventFunction`1 
---@field public initializePotentialDrag EventFunction`1 
---@field public beginDragHandler EventFunction`1 
---@field public dragHandler EventFunction`1 
---@field public endDragHandler EventFunction`1 
---@field public dropHandler EventFunction`1 
---@field public scrollHandler EventFunction`1 
---@field public updateSelectedHandler EventFunction`1 
---@field public selectHandler EventFunction`1 
---@field public deselectHandler EventFunction`1 
---@field public moveHandler EventFunction`1 
---@field public submitHandler EventFunction`1 
---@field public cancelHandler EventFunction`1 
local ExecuteEvents={ }
---
UnityEngine.EventSystems.ExecuteEvents = ExecuteEvents