---游戏物理碰撞层定义
GameLayers = {
  LAYER_PHY_GLOBAL = 0,
  LAYER_PHY_FLOOR = 1,
  LAYER_PHY_FLOOR_STOPPER = 2,
  LAYER_PHY_MODUL_COL_BALL = 3,
  LAYER_PHY_MODUL_NOCOL_BALL = 4,
  LAYER_PHY_MODUL_NOCOL_FLOOR = 5,
  LAYER_PHY_BALL = 6,
  LAYER_PHY_BALL_PEICES = 7,
}